imgcreate/kickstart.py
Recent versions of systemd changed to create a symlink pointing to a
nonexistent file in /run for networkd.
https://bugzilla.redhat.com/show_bug.cgi?id=1116651
=> kickstart: Handle resolv.conf being a nonexistent symlink

docs/livecd-iso-to-disk.pod, tools/livecd-iso-to-disk.sh
Help clarify confusion on filesystem and overlay space limitations.
=> Usage documentation update

imgcreate/creator.py
=> symlink /etc/mtab to /proc/self/mounts (#688277)

tools/livecd-iso-to-disk.sh
Ends up some of the parted commands may be translated. In this case it
was the unit command so always use C when calling parted.
=> Wrap all parted calls in LC_ALL=C (#1350253)

README
I presume the author meant 'note' here.
=> README Disambiguation

tools/liveimage-mount
Originally pull request #9 (with comments & responses), then #15, now rebased to master (omitting the OverlayFS feature as it has yet to be adopted).
=> liveimage-mount: rebased multiple updates

tools/livecd-iso-to-disk.sh, tools/liveimage-mount
```diff
Fix glitches in configuration file handling.
Caution message when overwriting multi image configuration files.
```
=> livecd-iso-to-disk & liveimage-mount: Multi Live Image Boot fixes.

tools/livecd-iso-to-disk.sh
While trying to preserve the device filesystem label across a
format change, a long name may be inappropriate for the new format.
`mkfs.fat -n` truncates a name longer than 11 bytes, and
`mkfs.ext[34] -L` truncate a label to 16 bytes.
Use `mkfs.fat` instead of the `mkdosfs` symbolic link to it.
Also clarify some label handling and
remove some useless exit status checks.
(This commit fixes [rhbz:1444530](https://bugzilla.redhat.com/show_bug.cgi?id=1444530) livecd-tools/issue/#59.)
=> livecd-iso-to-disk: Fix labeling of target device filesystem.

tools/livecd-iso-to-disk.sh
Configure the syslinux menu style to that provided in the source.
To assure a match between versions of the syslinux boot loader,
which is installed by the host, and the menu program selected by
the source, the menu program version on the host is copied to the
target device based on the menu style provided in the source.
(This means that for multi boot installations, the most recent host
and source may alter the version and menu style for all boots.)
Also, simplify selection of configuration file name.
Use more precise sed statements.
Allow better distinction of grub entries for replicated images on
the same device.
Provide a menu option 'Return to Multi Live Image Boot Menu' on
alternate individual boot menus of a multi boot installation.
This should fix the issue raised in Issue #34.
=> livecd-iso-to-disk: Adjust syslinux default menu style, as needed.

tools/liveimage-mount
Also, simplify util-linux wrapper functions.
And further Python3 compatibility.
=> liveimage-mount: Add support for OverlayFS overlays.

tools/livecd-iso-to-disk.sh
Avoid sed commands on a non-existent file.
(Bug reported in RHBZ #1494792 comment #3.)
=> livecd-iso-to-disk: Fix boot configuration for images lacking /EFI

tools/livecd-iso-to-disk.sh
If the script discovers a pre-existing image is installed at /LiveOS,
properly complete a multi Live image installation, if desired.
Also, fix a condition bug in the case where multi is not desired.
(Addresses RHBZ #1494792 comment 6.)
=> livecd-iso-to-disk: Allow auto --multi install.

imgcreate/fs.py, tools/editliveos
Fix overlay changing code.
Bind mount host's /etc/resolv.conf
Remove some code glitches.
See individual commits.
=> fs.py & editliveos:  A few fixes

tools/livecd-iso-to-disk.sh
Reorder code to improve multi image configuration;
Save previous config file with a suffix;
Duplicate grub.cfg in BOOT.conf file.
=> livecd-iso-to-disk: adjust efi boot configuration code.

tools/livecd-iso-to-disk.sh
Also, remove temporary mountpoint directory.
=> livecd-iso-to-disk: Simply mount read-only to test for flat_squashfs.

imgcreate/live.py
```code
Reorder xorrisofs options and arguments to match those in the
lorax live/x86.tmpl template because they receive more quality
control testing.
For the -e images/efiboot.img section,
remove -isohybrid-apm-hfsplus.
For the -e images/macboot.img section,
remove -isohybrid-gpt-basdat & -isohybrid-apm-hfsplus,
add -isohybrid-gpt-hfsplus.
Make this section conditional on the existence of
images/macboot.img.
Remove option -hide-rr-moved.
Unlike lorax, invoke the -iso-level 3 option based on the maximum
individual file size in the isodir, as should be.
```
=> live.py: harmonize xorrisofs arguments with lorax live/x86.tmpl

imgcreate/live.py
Refactored version of #180 
Obsoletes #180
Fixes #160
=> Initial AArch64 support for live media

imgcreate/fs.py
~~~
Lazy unmounting was originally introduced  in commit 73bd6807678f ("Do
lazy umounts to reduce the impact of umount issues.", 2010-07-24) as a
work-around for RHBZ#617844 and RHBZ#509427.
Unfortunately, lazy unmounting and then proceeding as if no error had
occurred is actively harmful: combined with the lazy nature of "losetup
-d", it enables writes pending within the chroot to modify / corrupt the
filesystem while it's being checked & modified by e2fsck, and/or captured
into the ISO image.
We've seen actual examples of this:
- https://bugzilla.redhat.com/show_bug.cgi?id=2007045
- https://bugzilla.redhat.com/show_bug.cgi?id=2038105#c45
- https://github.com/livecd-tools/livecd-tools/issues/221
Papering over a hard-unmount failure is never right; in all such cases,
the leaked …
=> imgcreate/fs.py: abort on hard-unmount failure

imgcreate/creator.py
...in LoopImageCreator. Fixes #246.
=> imgcreate/creator: add missing 'ops' argument to _stage_final_image

tools/livecd-iso-to-disk.sh
Select new boot/arch/loader directory for images. Allow filenames linux/initrd in addition to vmlinuz/initrd.img. Use full grub.cfg instead of stub. Delete EFI fallback exectuables.
Workaround: #262
=> livecd-to-iso-disk: F42 live format change workaround
