livecd-tools/livecd-tools

imgcreate/live.py

Some USB SCSI devices need this driver, for whatever reason dracut
doesn't add it by default.

Explicitly add the uas driver to the initrd (#1201983)

---

tools/livecd-iso-to-disk.sh

Installer images already have inst.stage2 on the cmdline, the LABEL
substitution takes care up setup for them.

litd: Don't add inst.stage2 to cmdline

---

imgcreate/live.py

Writing drivers+= to the dracut config ONLY installs those drivers. This
switches to use add_drivers+= so that dracut will pick up the usual set
of drivers and ADD the ones we select.
Resolves: rhbz#1192030

Use add_drivers for dracut config (#1192030)

---

tools/livecd-iso-to-disk.sh

Newer images don't have the "ro" on command line (since that seems to be
the default), but we still to mount the live directory read-write for
persistent overlay to work.

litd: add the "rw" argument even if there's no "ro"

---

imgcreate/kickstart.py

This should allow SELinux and static network configurations to coexist.

Stop truncating /etc/resolv.conf in SELinux module -- fixes #31

---

imgcreate/yuminst.py

On Fedora 24 with livecd-tools-23.3-1.fc24.x86_64 raising yum.Errors.RepoError without importing explicitly yum.Errors before the raise statement lead to:
00:02:22.248 Traceback (most recent call last):
00:02:22.248   File "/bin/livecd-creator", line 242, in <module>
00:02:22.249     sys.exit(main())
00:02:22.249   File "/bin/livecd-creator", line 218, in main
00:02:22.249     creator.install()
00:02:22.249   File "/usr/lib/python2.7/site-packages/imgcreate/creator.py", line 675, in install 
00:02:22.251     ayum.runInstall()
00:02:22.251   File "/usr/lib/python2.7/site-packages/imgcreate/yuminst.py", line 203, in runInstall
00:02:22.251     except yum.Errors.RepoError, e:
00:02:22.251 UnboundLocalError: local variable 'yum' referenced before assignment
Tracked on RHBZ: …

yuminst.LiveCDYum.runInstall: import yum.Errors

---

imgcreate/kickstart.py

It is possible for a live image to be built without FirewallD installed
in the target, either for the purpose of not configuring a firewall or
for the purpose of using an alternative.
So, now we check for if 'firewall-offline-cmd' is installed. If it
is not, then we throw a warning and ignore the configuration commands.
This PR obsoletes #38.

Check if FirewallD is installed before running ks firewall commands

---

HACKING
README

The mailing list references were out of date (Fedora hasn't been on the Red Hat listserv in years!), so this PR updates them.

Fix the mailing list reference

---

docs/livecd-iso-to-disk.pod
tools/livecd-iso-to-disk.sh

Remove unnecessary elements, consolidate related calls,
update the resetting of BOOTCONFIG files to current defaults,
and add a missing call for a 'rw' flag for all live installations,
which fixes https://bugzilla.redhat.com/show_bug.cgi?id=1418315
This commit also changes labels globally as requested in the second commit of PR #43.

livecd-iso-to-disk: Cleanup sed statements

---

tools/livecd-iso-to-disk.sh

Reverts a46804a from 2010, which fixed
https://bugzilla.redhat.com/show_bug.cgi?id=583658
We now use wipefs -a and newer utilities, which seem to fix issue.

livecd-iso-to-disk: Remove checkLVM() as it seems unnecessary now.

---

docs/livecd-iso-to-disk.pod
tools/livecd-iso-to-disk.sh

```diff
Allow uncompressed live persistence without an overlay.
Allow reuse of an existing overlay for a new installation with
--reset-overlay.
Also harden code to source paths with spaces,
prevent spaces in $LIVEOS targets,
support btrfs filesystem label,
reorder some code blocks, and
update copyright date.
```

livecd-iso-to-disk+pod: Add --no-overlay & --reset-overlay options.

---

docs/livecd-iso-to-disk.pod
tools/livecd-iso-to-disk.sh

Add new `--nobootmsg` and `--nomenu` options to automatically boot
the 'linux' label item.
submitted by: @havealoha

livecd-iso-to-disk+pod: Add options for automatic boot.

---

tools/livecd-iso-to-disk.sh

The recent rework introduced some bad sequencing and the partition
number failed to be determined.
(This should fix [rhbz#1437601](https://bugzilla.redhat.com/1437601) & [rhbz#1438578](https://bugzilla.redhat.com/1438578) and Issue #56.)
Testing revealed another code sequence problem when changing from
msdos to gpt partitions. (Also fixed.)

livecd-iso-to-disk: Fix --efi --format code sequence problems.

---

tools/livecd-iso-to-disk.sh

In commit 7b0198d, the freespace determination was mistakenly
hidden from the DVD installer code path.
This should fix [rhbz #1445507](https://bugzilla.redhat.com/show_bug.cgi?id=1445507) & [livecd-tools/issues/61](https://github.com/livecd-tools/livecd-tools/issues/61)

livecd-iso-to-disk: Fix freespace determination for DVD installer.

---

tools/livecd-iso-to-disk.sh

Distinguish $BOOTCONFIG from $BOOTCONFIG_EFI and don't use literal
/? here with extended regular expressions.
This should fix issue #72.

livecd-iso-to-disk: Fix sed for kernelargs.

---

docs/livecd-iso-to-disk.pod
tools/livecd-iso-to-disk.sh

Enable configuration of OverlayFS overlays with dracut version 045
or greater based initial boot images.  (dracut version 046 has been released.)
Flash storage devices may have capacity for multiple live images.
Allow a live booted or sourced device to be both source and the
target for a live image installation. Provide an easy flag, 'live',
to request a live booted source or target.
Support replication of LiveOS images with --copy-home and --copy-overlay options.

Add --overlayfs, --copy-home, --copy-overlay options & allow multi installs to live booted devices

---

imgcreate/kickstart.py

I'm currently using livecd-tools in a private project to make a custom live image for el7. With SELinux enabled, the build either aborts (enforcing mode) or is incorrect (permissive mode) due to setfiles aborting early due to 10 errors:
```
/etc/selinux/targeted/contexts/files/file_contexts: line 129 has invalid context system_u:object_r:gpfs_device_t:s0
/etc/selinux/targeted/contexts/files/file_contexts: line 1459 has invalid context system_u:object_r:ganesha_var_log_t:s0
/etc/selinux/targeted/contexts/files/file_contexts: line 1464 has invalid context system_u:object_r:ganesha_exec_t:s0
/etc/selinux/targeted/contexts/files/file_contexts: line 1521 has invalid context system_u:object_r:ganesha_var_run_t:s0
/etc/selinux/targeted/contexts/files/file_contexts: line 2370 has invalid context …
```

Use restorecon instead of setfiles for relabeling

---

tools/livecd-iso-to-disk.sh

Fixes overestimation of image size, RHBZ #1494792

livecd-iso-to-disk: Fix space evaluation for images lacking /EFI

---

Makefile
imgcreate/creator.py
imgcreate/debug.py
imgcreate/errors.py
imgcreate/fs.py
imgcreate/kickstart.py
imgcreate/live.py
imgcreate/util.py
tools/edit-livecd
tools/editliveos
tools/mkbackup
tools/mkbiarch

```
Edit a LiveOS image to merge a persistent overlay, insert files,
clone a customized instance, adjust the root or home filesystem or
overlay sizes, seclude private or user-specific files, rebuild the
image into a new, .iso image distribution file, and refresh the
source's persistent filesystem overlay. See editliveos --help.
Uses the Device-mapper mirror target to copy the root filesystem,
merging a persistent DM overlay, if present. OverlayFS overlays
are merged by a standard copy of the mounted root filesystem.
```
Note: Python3 was required for lack of hawkey module in Python2
```
import hawkey
ImportError: No module named hawkey
```
Note also: comment on efdf984

editliveos: A full featured replacement for tools/edit-livecd.

---

tools/livecd-iso-to-disk.sh

In Fedora 27, multiple BOOT*.EFI files are included in /EFI/BOOT.
Accommodate this situation during boot configuration.
This will avoid the unnecessary creation of $SOURCE.iso.0  $SOURCE.iso.1 $SOURCE.iso.2 files by dumpet.

livecd-iso-to-disk: Accommodate multiple BOOT*.EFI files.

---

tools/livecd-iso-to-disk.sh

Include overlay size in disc space report.
Exclude DM_snapshot_cow overlays from OverlayFS boot configuration
on --reset-overlay installations.

livecd-iso-to-disk: Fix overlay size reporting & type testing.

---

tools/livecd-iso-to-disk.sh

Test for file presence before attempting copy.
Fixes https://github.com/livecd-tools/livecd-tools/issues/82
I don't understand this section of code introduced almost 10 years ago with commit ceb818924b458b273293b17dd54b482b4581b528, but the patch allows the install script to complete and my test USB device booted properly.

livecd-iso-to-disk: Fix faulty --efi boot config code.

---

tools/livecd-iso-to-disk.sh

In a previous commit (aec80bc61), the step that set legacy_boot on
the EFI System Partition was removed. The result of that was an
inability to boot the disk via legacy BIOS-based booting.

livecd-iso-to-disk: Revert change that broke EFI/MBR hybrid booting

---

docs/livecd-creator.pod

The "man livecd-creator" information is not consistent with
"livecd-creator --help", should update the manpage info.
Signed-off-by: Zhang Xianwei <zhang.xianwei8@zte.com.cn>

Update livecd-creator manpage with info about imcomplete options

---

imgcreate/util.py

Since Python 3.6, Popen can accept an encoding to use for encoding
and decoding stdin, stderr, and stdout. Previously, call() did not
perform any decoding causes b'...' strings to be dumped into the
debug logs. Additionally, rcall() can be simplified slightly using
the same Popen feature.

util.py: Captured output from subprocesses should always be decoded.

---

imgcreate/kickstart.py
imgcreate/live.py
imgcreate/util.py

While testing projects with the new pykickstart 3.9 release, I ran in to some issues with livecd-tools.  First, the get_modules() stuff in livecd-tools can be removed because that has been gone from pykickstart for a while.  Second, in imgcreate/util.py, I ran in to some problems with io.open and UTF-8 encoding.  Adjusted the way the function works a bit and things seem to be behaving fine.

Fix two problems found in livecd-tools

---

imgcreate/live.py

imgcreate/live.py (__copy_efi_files): Add a required flag to the files.
Set it to True for the existing 3 files. But if set to False, just skip
the file if it is missing, and neither complain nor fail. Add
/boot/efi/EFI/*/gcdia32.efi to copy to /EFI/BOOT/grubia32.efi with
required=False.
Adds support for https://fedoraproject.org/wiki/Changes/32BitUefiSupport
Verified to do the right thing both with a Kannolo 27 x86_64 kickstart
(32-bit UEFI supported, gcdia32.efi gets copied) and with a Kannolo 26
x86_64 kickstart (32-bit UEFI not supported, gcdia32.efi is absent and
is skipped without producing an error).
Fixes #95.

imgcreate: Copy gcdia32.efi in __copy_efi_files if it exists (#95)

---

imgcreate/kickstart.py

restorecon doese not work inside the chroot, because there is no selinuxfs mounted on
/sys/fs/selinux, leading to no loaded selinux policy being loaded.
Setfiles bypasses the loaded policy, and just uses the installed policy.
This reverts commit 1c2307ce8b5150265f60afd7cf8a5749a1d26f9e.

Revert "Use restorecon instead of setfiles for relabeling"

---

imgcreate/live.py
tools/editliveos

This patch has been used successfully used in Fedora/RISC-V.
Signed-off-by: David Abdurachmanov <david.abdurachmanov@gmail.com>

Add support for RISC-V (riscv64)

---

imgcreate/dnfinst.py

There's a bug / overly-clever-design flaw in DNF 3 that prevents
us appending to config values that appear to be lists, even
though lists should be mutable objects and this *ought* to work
(and did work in DNF 2):
https://bugzilla.redhat.com/show_bug.cgi?id=1595917
This works around it.
Signed-off-by: Adam Williamson <awilliam@redhat.com>

DNF 3: workaround a bug with config values that are lists

---

tools/livecd-iso-to-disk.sh

This should fix Issue #104 on capable filesystems where mode 0600 is suggested for swap.img by mkswap and swapon.
The second commit bypasses a useless question/option on a --skipcopy invocation.

livecd-iso-to-disk: Tighten permissions on some files. & Skip useless question on --skipcopy.

---

imgcreate/live.py

With Python3, map() returns an iterator instead of a list as it does in Python2.
Avoid map() since we already have a for loop to process the collection of files.
This should fix Issue #94 (untested).

live.py: Fix unreported logging.error

---

imgcreate/dnfinst.py

See https://bugzilla.redhat.com/show_bug.cgi?id=1595917 again.
This is a follow-up to 2cbd239 - after I reported the bug,
upstream changed in DNF 3.6 to present these values as tuples
rather than lists, to indicate that they cannot be mutated. So
we can't add a list to the retrieved value, like we did before,
but using += (tuple) like this seems to work both in DNF 3.6
and in older DNFs.
Signed-off-by: Adam Williamson <awilliam@redhat.com>

Handle dnf config option showing as tuple, not list, in DNF 3.6

---

README
tools/editliveos
tools/livecd-iso-to-disk.sh

Also, clarify a few points, and fix typo.
\+

README: Update to include --flat-squashfs option. + fixes in litd & elos

---

imgcreate/kickstart.py

SELinux context is not properly set because setfiles command is not run after chroot.
Fixes #106

Run setfiles after chroot

---

docs/livecd-iso-to-disk.pod
tools/editliveos
tools/livecd-iso-to-disk.sh

~~~txt
With large capacity flash storage devices it is convenient to load
multiple live, netinstall, even full install images onto one device.
Also,
Allow interactive input of the --livedir directory name when that
option is omitted;
Always backup previous boot configuration files when present;
Slightly improve debugging & script comments;
Update documentation.
~~~
editliveos: Accommodate netinstall in multi boot configuration files.
~~~txt
Adjust the sed string editing commands to the boot configuration files
so as to accommodate the differing boot lines.
Also,
Propagate LICENSE & Fedora-Legal-README.txt files to new .iso files;
Slightly simplify sed command construction;
Synchronize redundant configuration files and backups;
Eliminate a long try: block in the refresh() function;
Update …

livecd-iso-to-disk+pod, editliveos: Support netinstall .isos and as multi install.

---

tools/livecd-iso-to-disk.sh

Commands that read too soon afterwards can result in `not a block device` errors
Signed-off-by: Steve Bonds <sbonds@gmail.com>

`udevadm settle` needs some time to settle

---

imgcreate/live.py

efiboot.img & macboot.img are in /images/,
enable iso file sizes > 4 GiB - 1.

live.py: Update xorrisofs_options for x86 images.

---

tools/livecd-iso-to-disk.sh

Take advantage of this option to stop waiting if file exists.

livecd-iso-to-disk: Use -E, --exit-if-exists option to udevadm settle.

---

imgcreate/live.py

Follow the convention in official boot.iso created by lorax.

live.py: Store EFI boot images in /images/.

---

tools/livecd-iso-to-disk.sh

Replace gvfs-copy with gio. Fixes RHBZ# 1665756, courtesy Bruce Jerrick.

livecd-iso-to-disk: Update test for 'gio' presence.

---

imgcreate/fs.py
tools/editliveos
tools/livecd-iso-to-disk.sh
tools/liveimage-mount

~~~~sh
Don't assume the default installation directory is /LiveOS; check
the default menu label in the boot configuration file.
Escape special characters in livedir, title, & label strings for
sed regex and replacement strings.
Save multi menu label blocks in the /syslinux configuration file
for restoration on an overinstall of the default installation.
Handle the --force option properly with multi image installs.
Use the -E, --exit-if-exists option to udevadm settle in fs.py and
liveimage-mount for the cow and overlay loop device.
Update copyright dates.
~~~~

Make --livedir & --multi handling more robust.

---

imgcreate/kickstart.py

Now that urlgrabber works natively on Python 3, we can use it
again and take advantage of its better semantics and smarter
protocol handling.

imgcreate/kickstart: Use urlgrabber again instead of urllib

---

imgcreate/fs.py
tools/editliveos
tools/liveimage-mount

Also take advantage of the new (Python 3.2) exist_ok parameter of
os.makedirs() and apply these features to the bind mounting of
/etc/resolv.conf in editliveos and liveimage-mount.
Without these changes, those applications choked on the symbolic
link provided in the current version of Fedora 33 Workstation Live.

BindChrootMount: Expand this class to include bind mounting of files.

---

docs/livecd-creator.pod
imgcreate/fs.py
imgcreate/live.py
tools/editliveos
tools/livecd-creator

```sh
Enable greater control over image compression via mksquashfs
options.
Interpret xz1m as "xz -b 1M -Xdict-size 1M -norecovery".
Enter multiple compression arguments as one string, i.e.,
--compression-type "type arg1 arg2 ...".
Update the documentation.
Use the extended option 'discard' for e2fsck of the root file
system to reduce its size.
Also, eliminate some stray whitespace in fs.py, and
use spaces to separate multiple arguments consistently
in editliveos.
```
This is a more general alternative to PR #163.

imgcreate: Allow more SquashFS compression options.

---

imgcreate/dnfinst.py

I believe this is probably the cause of
https://bugzilla.redhat.com/show_bug.cgi?id=1886567 , which broke
Rawhide and F33 composes today. dnf itself seems to always pass
this as a list or a tuple. The dnf API docs say "`pkg_types` is a
sequence of strings determining the kinds of packages to be
installed"; according to Python docs, lists, tuples and range
types are "sequences", but sets are not, so technically we are
out of bounds here. I believe this worked before this dnf commit:
https://github.com/rpm-software-management/dnf/commit/4d991f61
and upstream *could* probably tweak things to accept sets again,
but it seems reasonable to fix it here.
Signed-off-by: Adam Williamson <awilliam@redhat.com>

Pass package_types to dnf base group_install as tuple, not set

---

tools/livecd-creator

It's more helpful to the user if we don't combine "you didn't give me a
kickstart file" and "you gave me a kickstart file, but it doesn't
exist".
In addition to giving separate error messages for the two cases, the
"you gave me a kickstart file, but it doesn't exist" says what kickstart
file it thinks it's looking for, which will help users catch syntax
errors.
Fixes #174

Separate the errors for no ks specified and file not found

---

Makefile

After testing the master branch version of livecd-tools I attempted to uninstall it. However I found that many files that were installed via "make install" were still present after "make uninstall". I updated the uninstall section as follows:
1. Added lines to uninstall additional scripts installed in /usr/bin.
2. Added lines to remove man pages.
3. Fixed path to remove files under /usr/share/doc; the uninstall section tried to remove a versioned path but the install used an unversioned path.

Add missing files to uninstall section of makefile

---

imgcreate/live.py

This should fix issues where it's being referenced directly.
We generally expect Dracut to be used, so the value is set to true
by default.
Fixes #172

imgcreate/live: Add missing variable "_isDracut"

---

imgcreate/kickstart.py

When kickstart-file (--config parameter to livecd-creator) is located in current directory, urlgrabber.urlgrab() (without filename= paramater) will try to download the file using the basename of the path argument, resulting in overwriting the kickstart file. The result is a kickstart file of 0 bytes.
This patch adds a filename parameter to a hidden file in the current directory to avoid overwriting the original kickstart file. After being parsed, the temporary file is deleted.

prevent urlgrabber.urlgrab() from overwriting kickstart-file

---

imgcreate/live.py

Without this, the following error occurs:
`xorriso : FAILURE : -as genisofs: Unrecognized option '-isohybrid-gpt-basdat-isohybrid-mbr'`
Fixes #186

imgcreate/live: Add missing comma for xorrisofs options

---

imgcreate/live.py

#188 create efi image files under /isolinux, not /images

place efiboot.img and macboot.img in /isolinux

---

imgcreate/live.py

Se issue #190. Image tested ok with this patch for CentOS 8.4 with both bios end efi.

rearrange xorrisofs options to make image efi bootable

---

imgcreate/live.py

A path of initial location before copying files to the isodir was checked.
Let's better check the real location which will be fed to mkefiboot bellow.

Fix check if EFI bootloader exists

---

imgcreate/live.py

It was made on x86 (just because ISOs are made for both EFI and non-EFI) but was not in aarch64
This duplication of code looks ugly but I don't know how to make it better

mkdir isolinux on aarch64

---

imgcreate/live.py

Fixes: f5d76fa3748 ("place efiboot.img and macboot.img in /isolinux")
That commit forgot to change "images" to "isolinux" for aarch64.

Fix missync of locations of efiboot.img

---

imgcreate/live.py

I do not know what /usr/lib/anaconda-runtime/checkisomd5 is and when it existed,
it does not exist in modern Anaconda
chrootentitycheck() prints error message when it tries to find not existing binary
and then does not print anything when the second variant is found. It is confusing.

Modernize detection of checkisomd5

---

imgcreate/live.py

When using bios, the live image is the default option in the boot menu. However when using efi, the default is the second entry ("Troubleshooting"). This PR changes the default under efi so that bios and efi behaves the same and the live image is the default for both.

make live image the default boot option

---

docs/livecd-iso-to-disk.pod
imgcreate/fs.py
imgcreate/live.py
tools/editliveos
tools/livecd-iso-to-disk.sh
tools/liveimage-mount

A cumulative update, best reviewed by testing.
```
Enable formatting of a separate EFI System Partition and Apple HFS+ boot
partition based on the files efiboot.img and macboot.img in the /images
directory of the source.  This means EFI booting is possible with overlay
sizes as large as the free space on the primary partition.
Support F2FS type formatting for the device root, home, or overlay
filesystems.
Provide a GRUB EFI boot binary with basic F2FS filesystem support for
x86_64 architecture systems.
Provide boot support for F2FS extra_attr formatted discs with an EFI Boot
Stub loader from dracut, as GRUB support for this format is faulty at
this time.
Allow conversion of the root filesystem type between ext[234], btrfs, xfs,
& F2FS and their available block sizes with editliveos.
Allow …
```

livecd-iso-to-disk & editliveos: Expand partitioning and filesystem support

---

imgcreate/live.py

Since live.py supports rebuilding .iso images from existing .iso image
sources, support either of these locations for the xorrisofs options.

live.py: Support either /images or /isolinux directories for efi images.

---

config/livecd-fedora-minimal.ks
config/livecd-mageia-minimal-i586.ks
config/livecd-mageia-minimal-x86_64.ks
imgcreate/creator.py
imgcreate/kickstart.py

Authconfig compatibility tool (from authselect-compat) will be removed from Fedora 35:
https://fedoraproject.org/wiki/Changes/RemoveAuthselectCompatPackage
---
Mageia does not seem to have authselect. Are those kickstarts used by the tool
any way?

switch from authconfig to authselect

---

imgcreate/live.py

Adding dracut mudule livenet makes it possible to boot the live image via PXE and loading the root image via http(s)/ftp/tftp

add livenet dracut module to allow for pxe boot

---

README
docs/livecd-iso-to-disk.pod
imgcreate/fs.py
imgcreate/util.py
tools/editliveos
tools/livecd-iso-to-disk.sh

Preserve any extra kernel arguments that have been added by editliveos
or manually to the source boot configuration files.
Also:
- Add a bind mount to the host root filesystem for editliveos --script
or shell so as to ease access to host files from the install chroot.
- Improve some error handling & reporting.
- Adjust some space accounting & reporting for filesystem variations.
- Enable the ext4 64bit feature if the host's SYSLINUX version >= 6.04
- Update all boot configuration files upon editliveos refresh.
- fsck filesystems upon editliveos refresh.
- Fix a --refresh-only bug in editliveos.
Detect when a new kernel has been installed and update the working
copies to the newer version for both the new .iso image and a
refreshable source, including a currently booted LiveOS image. (The …

livecd-iso-to-disk & editliveos: Preserve extra-kernel-args from source.  Refresh vmlinuz & initrd.img upon kernel updates.

---

imgcreate/live.py

The 'unicode.pf2' font file for grub2 does not exist in
'/boot/efi/EFI/' any more in Fedora 35, and causes image build
fail. Use '/usr/share/grub/unicode.pf2' which belongs to
'grub2-tools' package instead.

Copy 'unicode.pf2' from correct path

---

tools/livecd-creator

This is a total hack, but in order to make sure the library is loaded
from the build host and not from the target chroot we need to do this.
This also means that the spec needs to Require: systemd-libs

Preload the libnss_systemd library (#2007045)

---

imgcreate/fs.py

Fix issue #233 with editliveos unnecessarily bind mounting a file
under /run leading to an unmount failure.
`/etc/resolv.conf` is not present in earlier versions but the Fedora 36 image includes it as a link to `../run/systemd/resolve/stub-resolv.conf`.

fs.py:  Avoid bind mounting an existing file target.

---

imgcreate/creator.py
imgcreate/kickstart.py

This patch corrects several issues with the setfiles SELinux relabel command. The issues become apparent when the host and guest policies differ. This patch is required to build a (functioning) selinux-enforcing Alma 8 image using a Fedora 35 host. There are probably many other host/guest combinations which are also affected.
By default, setfiles consults the kernel's loaded sepolicy if there is one. You can demonstrate this on a selinux-enabled system with strace:
sudo strace -etrace=file \
setfiles -Fvn \
/etc/selinux/targeted/contexts/files/file_contexts \
/dev/null
This does a dry-run relabel of /dev/null. The -n option prevents any changes from being made. Observe that strace reports
> openat(AT_FDCWD, "/sys/fs/selinux/context", O_RDWR|O_CLOEXEC) = 4
which is an indication that …

imgcreate/kickstart.py: correct setfiles relabeling

---

tools/livecd-iso-to-disk.sh

Also quiet some cleanup code, and
improve read-only test on loop device.

livecd-iso-to-disk: Remove useless test to fix issue #237

---

imgcreate/creator.py

Fix a bug introduced by my #236.
In 67081a3657, bind mounts are unmounted before the filesystem is relabeled with `setfiles`. The function which performs the unmount executes
umount /sys/fs/selinux
without first executing
umount /sys/fs/selinux/load
This can—but may not always—lead to a dreaded "*leaked a reference to the filesystem*" build error.
Fix by ensuring `/sys/fs/selinux/load` is unmounted first, just like [`ImageCreator.unmount()`](https://github.com/livecd-tools/livecd-tools/blob/867b9e7c477c5894586c55af7031da489e6ba6ff/imgcreate/creator.py#L583) does. We do not re-mount it afterwards because we shouldn't need to do anything more with SELinux after the relabel completes.

imgcreate/creator.py: fix SELinux unmount order

---

tools/livecd-iso-to-disk.sh

FIX the unexpected exit when using `livecd-iso-to-disk` and setting target as `live`.
Just one line modification.

fix: OR operator bug when target is 'live'

---

imgcreate/kickstart.py

Let's suppose we have a kickstart file which includes another file using relative path, and both are stored in a subdirectory relative to $PWD:
```
subdir/a.ks  # contains '%include b.ks'
subdir/b.ks
```
Now when trying to build ISO with `--config=subdir/a.ks`, it gets copied to $PWD/.kstmp.$PID. This breaks the %include command, cause b.ks is in the $PWD/subdir, not in $PWD where temporary copy of a.ks is.
To avoid overcomplicating solution, let's open the file directly when it appears to exist on local file system, without using urlgrabber; and try to download it only when it does not exist. This solves the issue, cause pykickstart is able to correctly figure out subdirs and relative includes when it gets the original file location.

imgcreate/kickstart: parse kickstart directly when it's a local file

---

imgcreate/creator.py

This seems counter intuitive, but is actually useful when user wants to include mandatory `@core` packages, but skip default ones, as there is no other way to do that but something like:
```
%packages --nocore
@core --nodefaults
```
Similarly, with this fix this approach may be used to select optional packages from `@core` group.

imgcreate/creator: allow including @core group when --nocore is used

---

imgcreate/util.py

`split()` method without any arguments will return list of words, using whitespaces as separator, which then `logging.debug()` will output on separate lines,
making
mess
like
this.
Use `splitlines()` to get a list of lines and print it directly to solve that problem. Note `rstrip` is no longer needed (due to `keepends=False`), and the `break` must go away cause otherwise we would drop all output following an empty line.
Tested in Alma 9 container. Before:
```
Formating ext4 filesystem on /dev/loop0
Formating args: ['mkfs.ext4', '-F', '-L', '_test_vm-2022091', '-m', '1', '-b', '4096', '/dev/loop0']
mke2fs
1.46.5
(30-Dec-2021)
Discarding
device
blocks:
0/1048576
done
Creating
filesystem
with
1048576
4k
blocks
and
...
```
After:
```
Formating ext4 filesystem on /dev/loop0
Formating args: …
```

imgcreate/util: don't print every word on its own line

---

imgcreate/live.py
tools/livecd-creator

With command line option "--nomac", livecd-creator skips the call to mkefiboot that creates a hfs boot image. Useful for systems that does not have mkfs.hfsplus

add --nomac option to tools/livecd-creator to skip hfs image

---

imgcreate/live.py

3fe2b3927e21e8a81c53baae83243100acad3b0c fixed this for x64 systems, but
the outdated paths were still present for arm64 builds.

Fix 'unicode.pf2' path for arm64

---

README
docs/livecd-creator.pod
imgcreate/creator.py
imgcreate/dnfinst.py
tools/livecd-creator

This is an alternative to PR #235 with a more dnf-centric implementation.
At present, the kickstart [dialect](https://docs.fedoraproject.org/en-US/fedora/latest/install-guide/appendixes/Kickstart_Syntax_Reference/#sect-kickstart-commands-repo) cannot represent GPG keys for package signing. Package signing is required to protect against potential supply-chain attacks from untrustworthy mirrors. We can bypass this kickstart limitation by making dnf load repo configuration from a `.repo` file or a directory of the same. This is exactly how dnf works on normal, live systems.
This patch series adds the following CLI arguments:
* `--repo`: adds one or more repositories using a dnf [configuration file](https://dnf.readthedocs.io/en/latest/conf_ref.html#repo-options) or directory, just as one …

Optionally obtain repository config from .repo file instead of kickstart

---

docs/livecd-creator.pod
imgcreate/creator.py
imgcreate/dnfinst.py
imgcreate/fs.py
imgcreate/kickstart.py
imgcreate/live.py
imgcreate/util.py
tools/editliveos
tools/livecd-creator
tools/liveimage-mount

```txt
imgcreate, editliveos: Refactor to Fedora 37 image layout.
Accommodate the GRUB-only boot .iso image layout.
Also,
In livecd-creator:
Enhance the interactive shell in livecd-creator with
a path-descriptive prompt string, and
additional bind mounts to facilitate ad-hoc customization
from the host shell.
Provide new livecd-creator options:
--syslinux    to select this BIOS boot option (default: False),
--dracut-args "[+]arg0 arg1 ..."  to configure the initrd image,
-o, --output <path>               the directory path for saving
the .iso image (default: '.').
Remove an obsolete import directive.
In dnfinst.py:
Remove an obsolete import directive.
In kickstart.py:
Provide 'Setting SELinux contexts...' message in the console
while the install root is being relabelled.
Adjust default …
```

imgcreate, editliveos: Refactor to Fedora 37 image layout.

---

docs/livecd-creator.pod
imgcreate/creator.py
imgcreate/dnfinst.py
imgcreate/live.py
tools/livecd-creator
tools/liveimage-mount

```txt
Use unsquashfs to decompress flattened image directly to the
_instroot.
Avoid kickstart installations when a change root shell is requested
in a livecd-creator session that employs a base-on image.  This
makes sequential editing of an image quicker.
Also:
Include F2FS drivers in the initrd.
Default to zstd compression to favor more rapid decompression.
Include the dracut modules dmsquash-live-autooverlay & overlayfs
among the defaults.
Revert the explicit omission of plymouth.
Rename dracut_args to dracut_conf_args to match their required
syntax.
Print a couple of console messages on the activity of the script at
longer operations.
Assure that mounts are unmounted in the necessary order.
Update documentation.
```
************************************
These changes have been tested …

Refactor to permit base-on of flattened SquashFS only images.

---

imgcreate/creator.py
imgcreate/dnfinst.py
imgcreate/kickstart.py

Closes #201.
Hopefully this is okay... I'm not confident at all in dnf internals, but:
a) it seems working (I was able to install nodejs-18 instead of non-modular nodejs-16 when building Alma 9.2 image using `module --name=nodejs --stream=18` command). Also the default stream (no `--stream`) and `--disable` seem working.
b) I took care this code does nothing when there are no `module` command(s) in kickstart file. However, previously the command was silently ignored, so it still may surprise someone, if they have `module` commands that now will start working.

imgcreate: support kickstart 'module' command

---

imgcreate/live.py

Is there some reason that "Troubleshooting" is the the default boot menu choise? If not please consider this PR to make booting the live image the default choice.

make live image default choice in boot menu

---

imgcreate/live.py

Without this I was not able to build Rocky 8 live image on a Rocky 9 host. Needed to be able to set "--compression-type xz".

use compression from command line in dracut config

---

tools/livecd-iso-to-disk.sh

Fallback to pulling kernel/initrd from pxeboot directory if isolinux/syslinux directories not present.
Sanity check kernel/initrd directory present.
Set up 100 MB ESP Partition if efiboot.img not present.
Set up dummy isolinux/syslinux config file if a non-EUFI boot config file is not present in iso and --efi specified.
Error if no --efi and non-UEFI boot config file not present.

Fedora 38+ (UEFI-only) live format change workarounds
